name: dialer hack

on:
 workflow_dispatch:
  inputs:
   commit_id:
    type: string
    required: true

jobs:
 build:
  name: build with gradle
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4
     with:
      fetch-depth: 1
   - name: JDK17
     uses: actions/setup-java@v3
     with:
      java-version: '17'
      distribution: 'temurin'
   - name: Setup go1.22+
     uses: actions/setup-go@v4
     with:
      go-version: '1.22.5'
   - name: download special firestack
     run: |
      mkdir 'app/libs'
      cd 'app/libs'
      wget -O firestack.zip --tries=3 "https://github.com/Lanius-collaris/firestack/archive/${{ inputs.commit_id }}.zip"
      unzip -q firestack.zip
   - name: build aar
     run: |
      cd "app/libs/firestack-${{ inputs.commit_id }}"
      export 'FOUT=../firestack.aar'
      ./make-aar nogo r
   - name: 'edit build.gradle'
     run: |
      sed -i "/fdroidImplementation/c fdroidImplementation files(\'libs/firestack.aar\')" 'app/build.gradle'
      sed -i -e '/crashlytics/d' -e '/gms/d' build.gradle 'app/build.gradle'
   - name: gradle assembleFdroidFullRelease
     run: |
      ./gradlew assembleFdroidFullRelease
   - name: Grab APK
     run: |
      export apk_path="$(find . -type f -iname '*.apk' | head -n1)"
      echo "APKFILE=${apk_path}" >> $GITHUB_ENV
   - name: upload
     uses: actions/upload-artifact@v3
     if: success()
     with:
      name: test.apk
      path: ${{ env.APKFILE }}
      if-no-files-found: error
